# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 29e80587f90265170a03f45d1aafd9e836d3324617001bc5112f422095e5fb6593a608e7a66452b4fcb5bcfc540b2ef3de1d52b9abff75b563efcd68a0473e2f

test:
  secret_key_base: 80edd26ad0dd382ad00d8ecd35a4230a5ea5ff3248f97864433b4e55708e8a18e52a50450081affbf6914ab32bdb7d3764612cae048c7f6ad0e4777c8c51bc81

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
